#!/bin/bash
sudo pacman-mirrors -g
sudo pacman -S yaourt --noconfirm
sudo pacman -Syyu --noconfirm
sudo pacman -S bash-completion --noconfirm
sudo sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j7"/g' /etc/makepkg.conf
yaourt -S libopenraw digikam kipi-plugins picard-git python-discid normalize libreplaygain reflac libquicktime python2-opengl python2-discid lua-socket twolame libva-vdpau-driver ttf-freefont vcdimager cdrkit dvdauthor qt5-imageformats --noconfirm
yaourt -S kdenlive movit frei0r-plugins sox --noconfirm
yaourt -S java-openjfx --noconfirm
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/
yaourt -S java-p7zip-binding --noconfirm
yaourt -S get_iplayer-git atomicparsley-largefile-hg perl-mp3-info perl-mp3-tag flvstreamer id3v2 --noconfirm
yaourt -S handbrake filebot python2-pillow xsane xsane-gimp sc-controller-git libzen puddletag tk --noconfirm
yaourt -S k3b cdrdao emovix transcode opusfile dvd+rw-tools --noconfirm
yaourt -S lutris python-evdev python-pyinotify --noconfirm
yaourt -S calibre --noconfirm
yaourt -S gramps graphviz rcs gtkspell3 python-pillow python-reportlab libgexiv2 osm-gps-map python-pyicu --noconfirm
yaourt -S pstoedit libmythes beanshell libmspack --noconfirm
yaourt -S ttf-mac-fonts --noconfirm
yaourt -S ttf-freefont ttf-hack ttf-symbola vcdimager xed twolame libva-vdpau-driver --noconfirm
yaourt -S ttf-ms-fonts --noconfirm
yaourt -S fonts-meta-base --noconfirm
yaourt -S fonts-meta-extended-lt
yaourt -S google-fonts-git --noconfirm
yaourt -S clementine --noconfirm
yaourt -S gtk3-print-backends --noconfirm
yaourt -S bluez-plugins bluez-utils bluez-plugins --noconfirm
yaourt -S lib32-libcups lib32-libexif lib32-libldap lib32-gnutls lib32-gsm --noconfirm
yaourt -S lib32-gstreamer0.10 lib32-libxcomposite lib32-libxslt lib32-libxxf86dga lib32-mpg123 lib32-openal lib32-v4l-utils --noconfirm
yaourt -S crossover --noconfirm
yaourt -S viber obs-studio --noconfirm
