#!/bin/bash
sudo pacman -S bash-completion --noconfirm
yaourt -S xcursor-neutral++ --noconfirm
sudo cp /usr/bin/nano /usr/bin/vi
sudo sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j7"/g' /etc/makepkg.conf
yaourt -S libopenraw digikam kipi-plugins picard python-discid libquicktime python2-opengl python2-discid lua-socket twolame ttf-freefont --noconfirm
yaourt -S frei0r-plugins sox --noconfirm
yaourt -S java-openjfx --noconfirm
yaourt -S get_iplayer-git atomicparsley-largefile-hg perl-mp3-info perl-mp3-tag flvstreamer id3v2 --noconfirm
ln -s /DATA1/Documents/ ~/Documents
ln -s /DATA1/Music/ ~/Music
ln -s /DATA1/Games/ ~/Games
ln -s /DATA1/Downloads/ ~/Downloads
ln -s /DATA2/Pictures/  ~/Pictures
ln -s /DATA2/Videos/ ~/Videos
yaourt -S handbrake filebot python2-pillow xsane xsane-gimp sc-controller-git libzen puddletag tk --noconfirm
yaourt -S lutris python-pyinotify --noconfirm
yaourt -S calibre --noconfirm
yaourt -S gramps graphviz rcs gtkspell3 python-reportlab libgexiv2 osm-gps-map python-pyicu --noconfirm
sudo pacman -R libreoffice-still-en-gb --noconfirm
yaourt -S libreoffice-fresh-en-GB pstoedit libmythes beanshell unixodbc postgresql-libs coin-or-mp libmspack --noconfirm
yaourt -S ttf-mac-fonts ttf-symbola --noconfirm
yaourt -S ttf-ms-fonts --noconfirm
yaourt -S fonts-meta-base --noconfirm
yaourt -S fonts-meta-extended-lt --noconfirm
yaourt -S ttf-google-fonts-git
yaourt -S clementine --noconfirm
yaourt -S gtk3-print-backends --noconfirm
yaourt -S bluez-plugins bluez-utils bluez-plugins --noconfirm
yaourt -S lib32-fontconfig lib32-libcups lib32-sdl lib32-libdbus lib32-libexif lib32-libldap lib32-libpulse lib32-gnutls lib32-gsm lib32-libxcomposite lib32-libxml2 lib32-libxslt lib32-libxxf86vm lib32-libxxf86dga lib32-mpg123 lib32-nss-mdns lib32-openal lib32-openssl lib32-v4l-utils lib32-giflib lib32-opencl-icd-loader lib32-gst-plugins-base-libs --noconfirm
yaourt -S crossover --noconfirm
yaourt -S viber obs-studio --noconfirm
yaourt -S wine --noconfirm
winecfg

## Make sure to add 'iommu=soft' and 'modprobe.blacklist=sp5100_tco' to the kernel options in /etc/default/grub
